FROM node:22-alpine 

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

ENV CI=true

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --config.confirmModulesPurge=fals

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]